# **Week 1: Intro to R and data types**
```
.------------------------------------.
|   __  ____  ______  _  ___ _____   |
|  |  \/  \ \/ / __ )/ |/ _ \___  |  |
|  | |\/| |\  /|  _ \| | | | | / /   |
|  | |  | |/  \| |_) | | |_| |/ /    |
|  |_|  |_/_/\_\____/|_|\___//_/     |
'------------------------------------'

```

## **Pre-Configurating the Notebook**

### **Switching to the R Kernel on Colab**

By default, Google Colab uses Python as its programming language. To use R instead, you’ll need to manually switch the kernel by going to **Runtime > Change runtime type**, and selecting R as the kernel. This allows you to run R code in the Colab environment.

However, our notebook is already configured to use R by default. Unless something goes wrong, you shouldn’t need to manually change runtime type.

### **Importing Required Datasets and Packages**
**Run the following lines of code**:

In [1]:
#Do not modify

setwd("/content")

# Remove `MXB107-Notebooks` if exists,
if (dir.exists("MXB107-Notebooks")) {
  system("rm -rf MXB107-Notebooks")
}

# Fork the repository
system("git clone https://github.com/ArwenNugteren/MXB107-Notebooks")

# Change working directory to "MXB107-Notebooks"
setwd("MXB107-Notebooks")

#
invisible(source("R/preConfigurated.R"))

Loading required package: ggplot2

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: tidyr

Loading required package: stringr

Loading required package: magrittr


Attaching package: ‘magrittr’


The following object is masked from ‘package:tidyr’:

    extract


Loading required package: IRdisplay

Loading required package: png

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘png’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: grid

Loading required package: knitr

Loading required package: jpeg

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘jpeg’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

**Do not modify the following**:

In [2]:
if (!require("testthat")) install.packages("testthat"); library("testthat")

test_that("Test if all packages have been loaded", {

  expect_true(all(c("ggplot2", "tidyr", "dplyr", "stringr", "magrittr") %in% loadedNamespaces()))

})

test_that("Test if all utility functions have been loaded", {
  expect_true(exists("skewness"))
  expect_true(exists("kurtosis"))
})

Loading required package: testthat


Attaching package: ‘testthat’


The following objects are masked from ‘package:magrittr’:

    equals, is_less_than, not

Test passed with 1 success 🌈.
Test passed with 2 successes 🥇.

# Dataset
You can load the dataset that will be analysed in Problem Solving Task 1 with the following R code.

In [6]:
data = read.csv("./datasets/student_wellness_dataset.csv")

head(data)
tail(data)

  Faculty     YearLevel ExerciseGroup StudyHours SleepHours StressScore
1 Business    1st Year  Moderate      19.53      5.84       25.6
2 Engineering 4th Year  High          12.52      6.33       40.3
3 Arts        1st Year  Low           27.78      6.20       37.0
4 Arts        4th Year  Low           24.58      8.00       25.0
5 Science     4th Year  Low           11.03      6.27       44.5
6 Science     3rd Year  Low           17.97      5.15       52.1
  ExamScore
1 76.2
2 58.9
3 69.8
4 69.6
5 47.6
6 70.5

    Faculty     YearLevel ExerciseGroup StudyHours SleepHours StressScore
215 Arts        2nd Year  Moderate      11.44      6.43       23.6
216 Science     1st Year  Moderate      10.27      8.07        5.8
217 Business    3rd Year  Low            8.13      7.78       27.9
218 Arts        3rd Year  Moderate       6.28      6.49       17.2
219 Arts        4th Year  Moderate      16.93      6.25       23.0
220 Engineering 2nd Year  High          12.55      7.92       20.1
    ExamScore
215 56.6
216 66.5
217 51.9
218 51.7
219 69.8
220 57.0

You are now ready to get started working on the Problem Solving Task!

Here is some more information about the dataset.  A sample of students is taking from a particular Univeristy to investigate the impact of student wellness on exam performance.  Each row in the dataset corresponds to a student.  The dataset has the following measurements:


*   Faculty: indicates which Faculty a student belongs to
*   YearLevel: indicates what year level the student is at
*   ExerciseGroup: indicates how much a student exercises as a categorical variable
*   StudyHours: indicates how long a student studies each week on average
*   SleepHours: indicates how long a student sleeps each night on average
*   StressScore: indicates a stress score for a student
*   ExamScore: indicates the score a student got on the exam

In [23]:
data$ExerciseGroup
Highs = ifelse(data$ExerciseGroup == "High",1,0)
sum(Highs)/length(data$ExamScore)

  [1] "Moderate" "High"     "Low"      "Low"      "Low"      "Low"
  [7] "High"     "Moderate" "Moderate" "Low"      "Moderate" "Moderate"
 [13] "Low"      "Moderate" "Moderate" "Moderate" "Moderate" "Low"
 [19] "Moderate" "Moderate" "Moderate" "High"     "Moderate" "Low"
 [25] "Low"      "Moderate" "Low"      "Moderate" "High"     "Moderate"
 [31] "Moderate" "Moderate" "Moderate" "Moderate" "High"     "Moderate"
 [37] "High"     "High"     "Low"      "Low"      "Low"      "Low"
 [43] "Low"      "Moderate" "Low"      "Moderate" "High"     "Low"
 [49] "High"     "Low"      "Low"      "Moderate" "Moderate" "High"
 [55] "Moderate" "High"     "Low"      "Low"      "High"     "High"
 [61] "High"     "Moderate" "Moderate" "High"     "Moderate" "High"
 [67] "High"     "Moderate" "High"     "High"     "Low"      "High"
 [73] "Moderate" "High"     "Moderate" "High"     "Moderate" "Low"
 [79] "High"     "Low"      "Moderate" "High"     "High"     "Moderate"
 [85] "Moderate" "Moderate" "Low"      "Moderate" "Moderate" "High"
 [91] "High"     "High"     "Low"      "Moderate" "Low"      "Moderate"
 [97] "Moderate" "High"     "Moderate" "Low"      "Low"      "High"
[103] "Moderate" "Low"      "Low"      "Moderate" "Low"      "High"
[109] "Moderate" "Low"      "Low"      "High"     "Moderate" "Moderate"
[115] "High"     "High"     "High"     "High"     "Moderate" "Low"
[121] "High"     "Moderate" "Moderate" "High"     "Low"      "Moderate"
[127] "Low"      "Moderate" "Low"      "Low"      "Low"      "Moderate"
[133] "Moderate" "Moderate" "High"     "Moderate" "Low"      "High"
[139] "Low"      "High"     "Low"      "High"     "Low"      "High"
[145] "Moderate" "High"     "Low"      "Moderate" "High"     "Moderate"
[151] "Moderate" "Moderate" "Moderate" "Moderate" "Moderate" "High"
[157] "Low"      "Low"      "High"     "High"     "Moderate" "Moderate"
[163] "Low"      "Low"      "Moderate" "Moderate" "Moderate" "Low"
[169] "High"     "High"     "Moderate" "Moderate" "Moderate" "High"
[175] "Moderate" "Low"      "High"     "High"     "High"     "Moderate"
[181] "Moderate" "Moderate" "High"     "High"     "Low"      "Low"
[187] "Moderate" "High"     "High"     "Low"      "Moderate" "Moderate"
[193] "High"     "High"     "High"     "Moderate" "Moderate" "Low"
[199] "Low"      "High"     "High"     "High"     "High"     "Moderate"
[205] "High"     "High"     "High"     "Low"      "Moderate" "Low"
[211] "High"     "Moderate" "Low"      "Moderate" "Moderate" "Moderate"
[217] "Low"      "Moderate" "Moderate" "High"

[1] 0.3181818

In [24]:
HighsN1stYear = ifelse(data$ExerciseGroup == "High" & data$YearLevel == "1st Year", 1, 0)
sum(HighsN1stYear)/length(data$YearLevel)

[1] 0.06363636

In [25]:
morethan30 = ifelse(data$StudyHours > 30, 1,0)
sum(morethan30)/length(data$StudyHours)

[1] 0.01363636

In [29]:

N = 100
Failures = 0:4
ExpectedFailures = Failures/1.25
samples <- sample(Failures, N, replace=TRUE, prob = ExpectedFailures)
samplestable = table(samples)
proportions <- samplestable/N
print(samplestable)
print(proportions)

samples
 1  2  3  4
12 14 38 36
samples
   1    2    3    4
0.12 0.14 0.38 0.36